### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by paralin** [tylerdave/prompter#3]
In python 3 there's no raw_input anymore.

**Comment by tylerdave** [comment]
It tries to use raw_input and upon a NameError it uses input so it should work on both 2.7 and 3.x. Is something not working for you on 3.x?

**Comment by paralin** [comment]
Running under python3 I got an error about raw_input not being defined when I tried to use prompter. Weird.

**Comment by tylerdave** [comment]
It seems to be working on 3.4 for me but I'd love to figure out what the problem is. Can you please tell me what version of Python you're using, the steps you take to reproduce the error, and the error message / traceback? Thanks!

**Comment by paralin** [comment]
I can't figure out how I produced the error now (it was last night at around 2am, so who knows). Sorry about that. Will let you know if I encounter it again.
