### ISSUE TITLE
Yesno default not intuitive

### ISSUE THREAD

**Issue by Hanse00** [tylerdave/prompter#4]
Taken from https://github.com/tylerdave/prompter/blob/master/prompter/__init__.py#L98

``` python
while True:
        response = get_input(prompt_text).strip()
        if response == '':
            return True
```

It seems to me that True is returned on an empty response, regardless of how the default parameter is set. Is this a bug, or have I completely missed something here?

Cheers!

Edit: After a little additional testing, I've found what I misunderstood.
Apparently the values True and False are always the same, but depending on if the default is Yes or No, they flip meaning, as they always mean "Was the default selected?".

I would argue that it would be more sensible to have "True" mean "Yes" and "False" mean "No" in all cases. How do you feel about this?

**Comment by tylerdave** [comment]
I agree!

If you'd like to change it and submit a pull request (with updated tests), I'd be likely to accept it.

**Comment by Hanse00** [comment]
I'll have a look at doing that then, expect a result in a couple of days.
